#!/bin/bash

for i in {1..99}
do
	ffmpeg -hide_banner -f lavfi -i color=c=green:s=400x400:d=3 -vf "drawtext=fontfile=/afs/ec.auckland.ac.nz/users/j/l/jlee923/unixhome/Project/assignment_03/Incorrect/wg_legacy_edition.ttf:fontsize=150: fontcolor=white:x=(w-text_w)/2:y=(h-text_h)/2:text=$i" $i.mp4
	ffmpeg -loglevel panic -i $i.mp4 -r 1 -f image2 -vframes 1 -s 400x400 -ss 0:0:1 $i{no}.jpg

	rm -r $i.mp4
done
