package a03.enumerations;

public enum Stats {
	HARDHIGHESTSCORE, EASYHIGHESTSCORE, HARDLOWESTSCORE, EASYLOWESTSCORE, APPSTARTTIME, NUMBEROFEASYPLAYS,
	NUMBEROFHARDPLAYS, EASYCUMULATIVESCORE, HARDCUMULATIVESCORE;
}
