package a03.view;

import javafx.fxml.FXML;

import javafx.scene.control.Button;
import javafx.scene.image.Image;
import javafx.scene.image.ImageView;

import java.io.File;

import a03.MainApp;
import javafx.event.ActionEvent;

public class LessThanTenController {
	
	@FXML private ImageView _imageView;
	@FXML private Button _record;
	private MainApp _mainApp;

	// Event Listener on Button.onAction
	@FXML
	public void handleBack(ActionEvent event) {
		_mainApp.mainMenuContents();
	}
	
	// Event Listener on Button[#_record].onAction
	@FXML
	public void handleRecord(ActionEvent event) {
		// TODO Autogenerated
	}
	
	public void setMainApp(MainApp mainApp) {
		_mainApp = mainApp;
	}
	
	public void setQuestion(){
		File file = new File(System.getProperty("user.dir")+"/Video/9.jpg");
		System.out.println(file);
		Image image = new Image(file.toURI().toString());
		_imageView.setImage(image);
	}
}
